### ISSUE TITLE
Can't get an image to build

### ISSUE THREAD

**Issue by edude03** [alexandergall/nixos-pxe-installer#2]
Sorry for opening essentially A support request, I'm not sure if this a bug or if I can't figure out how to use it. 

I followed the instructions on a nixos 18.09 machine as was able to build the installer, but using the example for how to build an image 

```
with import <nixpkgs> {};

let
  installImageConfig = {
    installImage = {
      nixpkgs.path = ./nixpkgs;
    };
  };
  installImage = (import <nixpkgs/nixos/lib/eval-config.nix> {
    modules = [ modules/install-image.nix
                installImageConfig ];
  }).config.system.build.installImage;
in
  with installImage;
    [ tarball config ]
``` 

I ran into a few strange issues. 

Following that example exactly, I ran into an error `error: cannot coerce a built-in function to a string, at /root/nixos-pxe-installer/modules/install-image.nix:62:20` after playing with the code in nix repl (and using print debugging) I found what happens is that `readlink -f` doesn't return anything.

If I remove the `readlink` on line 60, it returns an absolute path, but then I get an error, `unable to cd to /root/nixos-pxe-installer/nixpkgs` which occurs on line 77. 

I assume this script needs the nixpkgs to be in the nix store, so I also tried pre-"realising" the path by changing `nixpkgs.path = ./nixpkgs` to `nixpkgs.path = ${./nixpkgs}` which also returns `cannot cd to /nix/store/$sha-nixpkgs` from line 77. 

I also tried running this script as a non-root user, but it had the same behavior. Unfortunately, while I have Linux experience, I have no idea why `cd` doesn't work and haven't been able to find any reasons for it, so I was hoping you could help guide me to a solution.

Thanks!

**Comment by alexandergall** [comment]
nixpkgs doesn't need to be in the Nix store and you should not need root privileges at all. I've seen these symptoms when permissions on a directory in the path to the nixpkgs directory were too strict, e.g. when your home directory doesn't at least have the executable bit for "others" set (effectively, the Nix build daemon running as root needs to be able to change into the nixpkgs directory).

**Comment by edude03** [comment]
Hi @alexandergall thanks for the guidance. I tried to make the permissions as permissive as possible by copying the `nixpkgs` checkout to `/tmp/nixpkgs` and changing the permissions with `chmod -R 777 /tmp/nixpkgs` but unfortunately that still doesn't work.

One interesting thing I noticed though, I added `whoami` at line 77 and it returns `nixbld` though when I look at`/etc/shadow` there is no `nixbld` user, though there is `nixbld{1-32}` not sure if that's expected behavior or if that changed in nix 2.1 / nixos 18.09

**Comment by alexandergall** [comment]
It seems that 18.09 has some fundamental changes in the build systen :( In particular, the builder appears to run in a chroot where it only sees the Nix store and nothing else from the regular file system (e.g. no /home at all and /tmp is empty). I'll have to figure out how to deal with that. Note that you should be able to build an image for 18.09 on a 18.03 system, if that's of any help.

**Comment by alexandergall** [comment]
The thing that changed in 18.09 is that the default of the option `nix.useSandbox` changed to `true`. With that, the builder doesn't have access to the regular file system of the host. I don't really understand why they did that since it even breaks trivial stuff like `fetchgitLocal`. Anyway, the workaround is to add `nix.useSandbox = false` to your `/etc/nixos/configuration.nix`.

**Comment by edude03** [comment]
Thanks, this solved the issue for me, though should we close this issue or is there another way it can be solved without turning off sandboxing?

**Comment by alexandergall** [comment]
This should finally be solved by https://github.com/alexandergall/nixos-pxe-installer/commit/a869e15752c065ec339ff6a0c2b6936539f8e234

Part of this fix is the requirement that the `installImage.nixpkgs.path` option is set to an object in the Nix store. So, in case of a checked-out Git repository in `./nixpkgs`, you now have to use something like
```
with import <nixpkgs> {};

let
  installImageConfig = {
    installImage = {
      nixpkgs.path = builtins.path { path = ./nixpkgs; };
    };
  };
  installImage = (import <nixpkgs/nixos/lib/eval-config.nix> {
    modules = [ modules/install-image.nix
                installImageConfig ];
  }).config.system.build.installImage;
in
  with installImage;
    [ tarball config ]
```
