### ISSUE TITLE
useBinaryCache option breaks installation

### ISSUE THREAD

**Issue by edude03** [alexandergall/nixos-pxe-installer#5]
Looks like a regression was introduced in https://github.com/alexandergall/nixos-pxe-installer/commit/448cbe3fa64035f1b6b96e5808bba288ecd626c7#diff-2e716080a08972ecb7adf2548fed7affR176

When useBinaryCache is set to `true` the default, the value `"true"` is passed to nix-env causing an error.

**Comment by alexandergall** [comment]
Fixed in dd5c1cc2e2e51cceae153e3551957c6d58775822
